language: php
sudo: false
dist: trusty

php:
  - '7.1'
  - nightly

env:
  - PATCHES_TEST_SUITE=unit
  - PATCHES_TEST_SUITE=acceptance

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
        - env: PATCHES_TEST_SUITE=acceptance

cache:
    directories:
        - ./vendor

install:
    - composer self-update --no-interaction
    - composer install --dev --no-interaction

script:
    - ./vendor/bin/grumphp run
    - echo "${PATCHES_TEST_SUITE}"
    - if [ "${TRAVIS_PHP_VERSION}" != "7.1" ]; then ./vendor/bin/codecept run "${PATCHES_TEST_SUITE}"; fi;
    - if [ "${TRAVIS_PHP_VERSION}" == "7.1" ]; then ./vendor/bin/codecept run "${PATCHES_TEST_SUITE}" --coverage-xml; fi;

after_success:
    - if [ -f ./tests/_output/coverage.xml ]; then travis_retry ./vendor/bin/coveralls -v; fi;
